default:
  image: node

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - npm install
  artifacts:
    paths:
      - node_modules

lint-job:
  stage: test
  script:
    - echo "This job tests something"
    - npm run lint
  artifacts:
    paths:
      - node_modules

test-job 1/2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
  artifacts:
    paths:
      - node_modules

test-job 1/3:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - node_modules

deploy-prod:
  stage: deploy
  environment: production
  when: manual
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - npm run build
  artifacts:
    paths:
      - node_modules
