name: wheelie

services:
  backend:
    image: ethan.lo/wheelie
    build:
      context: .
      target: dev
    env_file:
      - path: .env
    ports:
      - "3000-3001:3000-3001"

  db:
    image: postgres:15
    restart: always
    expose:
      - "5432"
    ports:
      - "5000:5432"
    env_file:
      - path: ./.env
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    expose:
      - "80"
    ports:
      - "5050:80"
    env_file:
      - path: ./.env
    depends_on:
      - db

volumes:
  postgres:
