---
apiVersion: v1
kind: Namespace
metadata:
  name: wheelie-api-dev

---
apiVersion: v1
kind: Service
metadata:
  name: wheelie-db-service
  namespace: wheelie-api-dev
spec:
  selector:
    db: wheelie-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: wheelie-api-service
  namespace: wheelie-api-dev
spec:
  type: NodePort
  selector:
    app: wheelie-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: wheelie-pgadmin-service
  namespace: wheelie-api-dev
spec:
  type: NodePort
  selector:
    admin: wheelie-pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wheelie-api-deployment
  namespace: wheelie-api-dev
  labels:
    app: wheelie-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wheelie-api
  template:
    metadata:
      labels:
        app: wheelie-api
        tier: backend
    spec:
      containers:
        - name: wheelie-api
          image: ethan.lo/wheelie:dev
          ports:
            - containerPort: 3001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wheelie-api-db
  namespace: wheelie-api-dev
  labels:
    db: wheelie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      db: wheelie-db
  template:
    metadata:
      labels:
        db: wheelie-db
        tier: backend
    spec:
      containers:
        - name: wheelie-db
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: wheelie

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wheelie-pgadmin
  namespace: wheelie-api-dev
  labels:
    admin: wheelie-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      admin: wheelie-pgadmin
  template:
    metadata:
      labels:
        admin: wheelie-pgadmin
        tier: backend
    spec:
      containers:
        - name: wheelie-pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@pgadmin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: root
            - name: PGADMIN_LISTEN_PORT
              value: "80"
